# Generated by Django 6.1.1 on 2026-09-15 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='category',
            field=models.CharField(choices=[('F2L', 'F2L'), ('OLL', 'OLL'), ('PLL', 'PLL')], max_length=3),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solve',
            name='time',
            field=models.FloatField(),
        ),
    ]
