# Generated by Django 6.1.1 on 2026-09-15 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_algorithm_category_alter_algorithm_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='algorithm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.algorithm'),
        ),
    ]
