# Generated by Django 6.1.1 on 2026-09-15 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_solve_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.algorithm'),
        ),
    ]
