# Generated by Django 6.1.1 on 2026-09-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_solve_algorithm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solve',
            name='algorithm',
        ),
    ]
