# Generated by Django 6.1.1 on 2026-09-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_solve_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='algorithm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.algorithm'),
            preserve_default=False,
        ),
    ]
